version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/python:latest
    steps:
      # dependencies
      - run: 
          name: Install bats testing framework
          command: |
              git clone https://github.com/sstephenson/bats.git
              cd bats
              sudo ./install.sh /usr/local
              rm -rf ~/project/*
      # checkout project sources
      - checkout
      # tests suite execution
      - run: 
          name: Execute tests suite
          command: |
              make test
