version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/python:latest
    steps:
      # dependencies
      - run: git clone https://github.com/sstephenson/bats.git && cd bats && sudo ./install.sh /usr/local
      # checkout
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: make test
