version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/python:latest
    steps:
      # Install dependencies
      - run: git clone https://github.com/sstephenson/bats.git
      - run: cd project/bats
      - run: ./install.sh /usr/local
      - run: cd
      # checkout
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: make test
